schema_version: "1.0"
clients:
  - {client_id: client01, node_id: node01, partition: partition01, tpm: tpm01}
  - {client_id: client02, node_id: node02, partition: partition02, tpm: tpm02}
  - {client_id: client03, node_id: node03, partition: partition03, tpm: tpm03}
  - {client_id: client04, node_id: node04, partition: partition04, tpm: tpm04}
  - {client_id: client05, node_id: node05, partition: partition05, tpm: tpm05}
  - {client_id: client06, node_id: node06, partition: partition06, tpm: tpm06}
  - {client_id: client07, node_id: node07, partition: partition07, tpm: tpm07}
  - {client_id: client08, node_id: node08, partition: partition08, tpm: tpm08}
  - {client_id: client09, node_id: node09, partition: partition09, tpm: tpm09}
  - {client_id: client10, node_id: node10, partition: partition10, tpm: tpm10}
  - {client_id: client11, node_id: node11, partition: partition11, tpm: tpm11}
  - {client_id: client12, node_id: node12, partition: partition12, tpm: tpm12}
  - {client_id: client13, node_id: node13, partition: partition13, tpm: tpm13}
  - {client_id: client14, node_id: node14, partition: partition14, tpm: tpm14}
  - {client_id: client15, node_id: node15, partition: partition15, tpm: tpm15}

